version: ${APP_VERSION}

services:

  # database service
  database:
    container_name: my_database
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: ${DATABASE_PGDATA}
    volumes:
      - ${DATABASE_PGDATA}
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      - custom
    restart: always
    env_file:
      - .env

# application service
  fastapi-app:
    container_name: Games_Backend
    build: Fastapi_Games
    command: python main.py
    ports:
      - ${SITE_PORT}:${SITE_PORT}
    depends_on:
      - database
    restart: always
    networks:
      - custom
    env_file:
      - .env

networks:
  custom:
    driver: bridge
